title: <p align="center">Manoj Kumar Shah</p>
logo: /assets/img/Manoj_new.jpeg
description: 
  <p align="center">
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/manojshah2/">LinkedIn</a> |
    <a href="https://github.com/manojshah2/"> GitHub</a>

    <br>
    I'm working on java microservices, angular, Data Science, Machine Learning & NLP related problems
    Currently working in Infoedge India Ltd as Lead Software Engineer.
    <br>
  </p>




theme: jekyll-theme-minimal
